infinispan/infinispan-spring-boot

infinispan-spring-boot-starter-autoconfigure/src/main/java/infinispan/autoconfigure/embedded/InfinispanEmbeddedCacheManagerAutoConfiguration.java
infinispan-spring-boot-starter-autoconfigure/src/main/java/infinispan/autoconfigure/remote/InfinispanRemoteCacheManagerAutoConfiguration.java
infinispan-spring-boot-starter-autoconfigure/src/main/resources/META-INF/spring.factories

Instantiating Spring Cache automatically

---

README.adoc

Added Spring Cache support

---

README.adoc
infinispan-spring-boot-starter-test-remote/src/test/java/test/infinispan/autoconfigure/remote/CustomPropertiesTest.java
infinispan-spring-boot-starter-test-remote/src/test/resources/test-hotrod-client.properties

Added additional test for placeholders

---

infinispan-spring-boot-starter-bom/pom.xml

https://issues.jboss.org/browse/ISPN-9478

ISPN-9478 bom

---

infinispan-spring-boot-starter-bom/pom.xml
infinispan-spring-boot-starter-remote/pom.xml
pom.xml

https://issues.jboss.org/browse/ISPN-9471

ISPN-9471 adds query dsl dependency to inject RemoteCache as a bean

---

README.adoc
infinispan-spring-boot-starter-embedded/src/main/java/org/infinispan/spring/starter/embedded/InfinispanEmbeddedConfigurationProperties.java
infinispan-spring-boot-starter-remote/pom.xml
infinispan-spring-boot-starter-remote/src/main/java/org/infinispan/spring/starter/remote/InfinispanRemoteConfigurationProperties.java
pom.xml

https://issues.jboss.org/browse/JDG-2306

JDG-2306 doc edits for Spring Boot Starter

---

infinispan-spring-boot-samples/README.adoc
infinispan-spring-boot-samples/embedded/pom.xml
infinispan-spring-boot-samples/remote/pom.xml
infinispan-spring-boot-starter-embedded/pom.xml
infinispan-spring-boot-starter-embedded/src/main/java/org/infinispan/spring/starter/embedded/InfinispanEmbeddedCacheManagerAutoConfiguration.java
infinispan-spring-boot-starter-embedded/src/test/java/test/org/infinispan/spring/starter/embedded/InfinispanEmbeddedAutoConfigurationIntegrationTest.java
infinispan-spring-boot-starter-remote/pom.xml
infinispan-spring-boot-starter-remote/src/main/java/org/infinispan/spring/starter/remote/InfinispanRemoteCacheManagerAutoConfiguration.java
infinispan-spring-boot-starter-remote/src/test/java/test/org/infinispan/spring/starter/remote/IntegrationTest.java
pom.xml

https://issues.jboss.org/browse/ISPN-9789

ISPN-9789 fix incompatibilities giving spring5 complete support

---

infinispan-spring-boot-starter-embedded/src/main/java/org/infinispan/spring/starter/embedded/InfinispanEmbeddedAutoConfiguration.java
infinispan-spring-boot-starter-embedded/src/main/java/org/infinispan/spring/starter/embedded/actuator/InfinispanCacheMeterBinder.java
infinispan-spring-boot-starter-embedded/src/main/java/org/infinispan/spring/starter/embedded/actuator/InfinispanCacheMeterBinderProvider.java
infinispan-spring-boot-starter-embedded/src/test/java/test/org/infinispan/spring/starter/embedded/InfinispanEmbeddedEnableTest.java
infinispan-spring-boot-starter-remote/src/main/java/org/infinispan/spring/starter/remote/InfinispanRemoteAutoConfiguration.java
infinispan-spring-boot-starter-remote/src/main/java/org/infinispan/spring/starter/remote/actuator/RemoteInfinispanCacheMeterBinder.java
infinispan-spring-boot-starter-remote/src/main/java/org/infinispan/spring/starter/remote/actuator/RemoteInfinispanCacheMeterBinderProvider.java
infinispan-spring-boot-starter-remote/src/test/java/test/org/infinispan/spring/starter/remote/EnablingTest.java

https://issues.jboss.org/browse/ISPN-9735

ISPN-9735 Fix actuator provider creation

---

Jenkinsfile

https://issues.jboss.org/browse/ISPN-9820

[1.0.x] ISPN-9820 Remove release step from jenkins file

---

infinispan-spring-boot-samples/embedded/pom.xml
infinispan-spring-boot-samples/remote/pom.xml
pom.xml

https://issues.jboss.org/browse/ISPN-9855
Closes: https://github.com/infinispan/infinispan-spring-boot/issues/88

ISPN-9855 Upgrade to SB 2.1.2.RELEASE

---

infinispan-spring-boot-starter-remote/src/main/java/org/infinispan/spring/starter/remote/actuator/RemoteInfinispanCacheMeterBinderProvider.java

https://issues.jboss.org/browse/ISPN-9902
Closes #92

ISPN-9902 Corrects instanceof check

---

infinispan-spring-boot-samples/embedded/pom.xml
infinispan-spring-boot-samples/remote/pom.xml
pom.xml

https://issues.jboss.org/browse/ISPN-9913
closes #96

ISPN-9913 Upgrades to infinispan 9.4.6.Final

---

infinispan-spring-boot-samples/remote/src/main/java/org/infinispan/tutorial/simple/spring/remote/BasqueName.java
infinispan-spring-boot-samples/remote/src/main/java/org/infinispan/tutorial/simple/spring/remote/BasqueNamesCachingApp.java
infinispan-spring-boot-samples/remote/src/main/java/org/infinispan/tutorial/simple/spring/remote/BasqueNamesRepository.java
infinispan-spring-boot-samples/remote/src/main/java/org/infinispan/tutorial/simple/spring/remote/Reader.java
infinispan-spring-boot-samples/remote/src/main/resources/application.properties
infinispan-spring-boot-starter-remote/src/test/java/test/org/infinispan/spring/starter/remote/ApplicationPropertiesTest.java
infinispan-spring-boot-starter-remote/src/test/java/test/org/infinispan/spring/starter/remote/CustomPropertiesTest.java
infinispan-spring-boot-starter-remote/src/test/resources/test-application.properties
infinispan-spring-boot-starter-remote/src/test/resources/test-hotrod-client.properties

https://issues.jboss.org/browse/ISPN-9969

ISPN-9969 remote statistics tests

---

pom.xml

9.4.8.Final

---

pom.xml

Upgrade infinispan version
Closes #106

Upgrade to 9.4.11.Final

---

infinispan-spring-boot-samples/embedded/pom.xml
infinispan-spring-boot-samples/remote/pom.xml

It works  : https://issues.jboss.org/browse/ISPN-9977

ISPN-9977 change pom.xml configuration to run samples with java -jar

---

pom.xml

upgrade 1.5.19

---

pom.xml

- Upgrade Infinispan to 9.4.15.Final
- Upgrade SB 2.1.6.RELEASE

Upgrade Infinispan and Spring-Boot dependencies

---

infinispan-spring-boot-starter-embedded/pom.xml
infinispan-spring-boot-starter-remote/pom.xml
infinispan-spring-boot-starter/pom.xml

https://issues.jboss.org/browse/ISPN-10440

ISPN-10440 Add <name> tag to the missing poms

---

documentation/asciidoc/topics/attributes/product-attributes-spring.adoc
documentation/asciidoc/topics/attributes/product-attributes.adoc

https://issues.jboss.org/browse/ISPN-10531

ISPN-10531 product doc attributes

---

pom.xml

ISPN-10783 Upgrade to 9.4.16.Final and SB 2.2.0.RELEASE

---

pom.xml

https://issues.redhat.com/browse/ISPN-11141

[9.4] ISPN-11141 Spring Boot 2.2.2

---

infinispan-spring-boot-starter-embedded/src/main/java/org/infinispan/spring/starter/embedded/InfinispanEmbeddedAutoConfiguration.java
infinispan-spring-boot-starter-embedded/src/test/java/test/org/infinispan/spring/starter/embedded/InfinispanEmbeddedAutoConfigurationCustomizerIntegrationTest.java

https://issues.redhat.com/browse/ISPN-11195

ISPN-11195 Start the manager when it's fully configured

---

documentation/asciidoc/stories/assembly_getting_started.adoc
documentation/asciidoc/topics/config_examples/application.properties
documentation/asciidoc/topics/proc_marshalling.adoc
documentation/asciidoc/topics/proc_running_server.adoc

https://issues.redhat.com/browse/ISPN-11320

ISPN-11320 SB Starter docs for DG 8

---

pom.xml

Change-Id: Id4a03b1e8beb2207dc781516f31eb2d590713f47

Upgrade SpringBoot to 2.2.4.RELEASE

---

pom.xml

https://issues.redhat.com/browse/ISPN-11546

ISPN-11546 Upgrade to 2.2.6.RELEASE

---

Jenkinsfile-release

need to update the jenkinsfile-release for sb starter version as we did in https://github.com/infinispan/infinispan-spring-boot/pull/144

jenkinsfile for sb starter version

---

infinispan-spring-boot-starter-embedded/pom.xml
infinispan-spring-boot-starter-embedded/src/main/java/org/infinispan/spring/starter/embedded/InfinispanConfigurationCustomizer.java
infinispan-spring-boot-starter-embedded/src/main/java/org/infinispan/spring/starter/embedded/InfinispanEmbeddedAutoConfiguration.java
infinispan-spring-boot-starter-embedded/src/test/java/test/org/infinispan/spring/starter/embedded/InfinispanEmbeddedAutoConfigurationCustomizerIntegrationTest.java
infinispan-spring-boot-starter-embedded/src/test/java/test/org/infinispan/spring/starter/embedded/InfinispanEmbeddedAutoConfigurationIntegrationConfigurationTest.java
infinispan-spring-boot-starter-embedded/src/test/java/test/org/infinispan/spring/starter/embedded/InfinispanEmbeddedAutoConfigurationIntegrationConfigurerTest.java
infinispan-spring-boot-starter-embedded/src/test/java/test/org/infinispan/spring/starter/embedded/InfinispanEmbeddedAutoConfigurationIntegrationTest.java
infinispan-spring-boot-starter-embedded/src/test/java/test/org/infinispan/spring/starter/embedded/InfinispanEmbeddedEnableTest.java
infinispan-spring-boot-starter-embedded/src/test/java/test/org/infinispan/spring/starter/embedded/testconfiguration/GlobalConfigurerJmxDisabledConfiguration.java
infinispan-spring-boot-starter-embedded/src/test/java/test/org/infinispan/spring/starter/embedded/testconfiguration/InfinispanCacheTestConfiguration.java
infinispan-spring-boot-starter-remote/pom.xml
infinispan-spring-boot-starter/pom.xml
pom.xml

https://issues.redhat.com/browse/ISPN-11801

ISPN-11801 11.0.0.Dev05 and 2.2.7.RELEASE

---

infinispan-spring-boot-starter-remote/src/test/java/test/org/infinispan/spring/starter/remote/InfinispanJmxConfigurationTest.java
infinispan-spring-boot-starter-remote/src/test/java/test/org/infinispan/spring/starter/remote/IntegrationTest.java
infinispan-spring-boot-starter-remote/src/test/java/test/org/infinispan/spring/starter/remote/extension/InfinispanServerExtension.java
infinispan-spring-boot-starter-remote/src/test/java/test/org/infinispan/spring/starter/remote/testconfiguration/InfinispanCacheTestConfiguration.java
pom.xml

https://issues.redhat.com/browse/ISPN-11843

ISPN-11843 Upgrade to 11 and SB 2.3

---

infinispan-spring-boot-starter-remote/src/main/java/org/infinispan/spring/starter/remote/InfinispanRemoteAutoConfiguration.java

https://issues.redhat.com/browse/ISPN-12069

ISPN-12069 Hot Rod configuration

---

documentation/asciidoc/topics/attributes/product-attributes.adoc

https://issues.redhat.com/browse/ISPN-12306

ISPN-12306 9.4 SB versions

---

pom.xml

https://issues.redhat.com/browse/ISPN-12429

ISPN-12429 Upgrade for release to 11.0.4.Final

---

pom.xml

https://issues.redhat.com/browse/ISPN-12429

Upgrade 11

---

documentation/asciidoc/topics/attributes/product-attributes.adoc

https://issues.redhat.com/browse/ISPN-12545

[9.4.x] ISPN-12545 sb starter versions

---

pom.xml

* Align Junit5 & testcontainer version with ISPN
For some reason, the test suite isn't running with Junit 5.7.0. I'm aligning the versions with ISPN.

Testsuite is not running
